---
title: "Data Import"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r, setup}
library(tidyverse)
library(readxl)
library(haven)
```

## Read in some data

Read in the litters dataset.

```{r} 
litters_df= read_csv("./data/FAS_litters.csv")
spec(litters_df)
litters_df = janitor::clean_names(litters_df)
```

## Take and look at the data

Print in the console.

```{r}
litters_df
```

```{r}
head(litters_df)
```

```{r}
tail(litters_df)
```

```{r}
skimr::skim(litters_df)
```
## option to read csv

```{r}
litters_df= read_csv("./data/FAS_litters.csv", skip = 10, col_names = FALSE)
```

```{r}
litters_df= read_csv("./data/FAS_litters.csv", na = c("", "NA", 999))
```

check out `?read_csv()` for more information. 

## Other file formats

Read in an excel file.

```{r}
mlb_df = read_excel("./data/mlb11.xlsx")
```

```{r}
mlb_df = read_excel("./data/mlb11.xlsx", range = "A1:F7")
```

Read in an SAS File
```{r}
pulse_df = read_sas("./data/public_pulse_data.sas7bdat")
pulse_df
```

